### ISSUE TITLE
Discover bug

### ISSUE THREAD

**Issue by ZhangyigengMark** [dipique/everythingio#1]
I found an error running in VS, saying "trying to load a program with incorrect format". The error occurred in "everything"_ Setsearchw (qry) "statement. How should I deal with this problem? Thank you very much. Can you help me?

**Comment by dipique** [comment]
Can you provide the steps to reproduce the issue? I can try to help troubleshoot with you.

**Comment by dipique** [comment]
> I found an error running in VS, saying "trying to load a program with incorrect format". The error occurred in "everything"_ Setsearchw (qry) "statement. How should I deal with this problem? Thank you very much. Can you help me?

But as a start, note that this is using 64 bit Everything, so make sure you are using a 64 bit build of your application. Don't use 32 bit or "Any CPU".

**Comment by ZhangyigengMark** [comment]
> > 我发现在 VS 中运行时出错，说“试图加载格式不正确的程序”。错误出现在“everything”_Setsearchw(qry)“语句中。我该如何处理这个问题？非常感谢。你能帮我吗？
> 
> 但首先，请注意这是使用 64 位 Everything，因此请确保您使用的是 64 位构建的应用程序。不要使用 32 位或“任何 CPU”。

**Comment by ZhangyigengMark** [comment]
> > I found an error running in VS, saying "trying to load a program with incorrect format". The error occurred in "everything"_ Setsearchw (qry) "statement. How should I deal with this problem? Thank you very much. Can you help me?
> 
> But as a start, note that this is using 64 bit Everything, so make sure you are using a 64 bit build of your application. Don't use 32 bit or "Any CPU".

I solved it in this way. Thank you very much
